### ISSUE TITLE
Request to remove credential from source code

### ISSUE THREAD

**Issue by tekjau** [yuxinn/Razer-Bank#5]
Hi guys, 

Could you please remove the credentials or the organizer FQDN from these codes?
https://github.com/yuxinn/Razer-Bank/blob/79b62689640eb5142f40f3270706b065bd13610a/backend/main.go
https://github.com/yuxinn/Razer-Bank/commit/cb53bad80e8720158fa360a5c4a5fed533a1026d
Thanks.

**Comment by ahboon** [comment]
Removed.
